# Generated by Django 6.0.1 on 2026-06-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_phone_contact_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Feedback',
        ),
    ]
